### ISSUE TITLE
Video Single Category open video modal - Enhancements

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx-videos#10]
### Is your enhancement related to a problem? Please describe.
Video Single Category open video modal is not updated and have styling issues and missing information.

### Describe the solution you'd like
There is a new design for the Video Modal that offer a solution to this problem and update the style.

### Designs
[Video Single Category - Open Video Modal](https://projects.invisionapp.com/d/main?origin=v7#/console/19153622/417127451/inspect?scrollOffset=400)
<img width="428" alt="video-modals" src="https://user-images.githubusercontent.com/20842182/81714400-05d94200-9445-11ea-94e7-e36a89f44c72.png">

### Todo
- [x] Apply styles to Single Category video modal as per the new design
- [x] Apply mobile and tablet styles to Single Category video modal as per the new design
- [ ] Add video title, date, views and length meta tags as per the design
- [ ] Add video excerpt as per the design
- [ ] Add "View Video" button on the modal

### To Fix
- [x] Fix the modals global styling to adapt them to the design.
