### ISSUE TITLE
Videos Single View - Enhancements

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx-videos#11]
### Is your enhancement related to a problem? Please describe.
Single video templates are not updated and have styling issues and missing information.

### Describe the solution you'd like
There are new designs that offer solutions to these problems and updates to the Single Videos templates

### Designs
[Videos Single View](https://projects.invisionapp.com/d/main?origin=v7#/console/19153622/417263108/inspect?scrollOffset=580)
<img width="323" alt="single-video-view" src="https://user-images.githubusercontent.com/20842182/81716823-d4ae4100-9447-11ea-8f47-e9a34fbbf3b8.png">

[Video Single View No Comments](https://projects.invisionapp.com/d/main?origin=v7#/console/19153622/417116026/inspect?scrollOffset=568.888916015625)
<img width="648" alt="video-single-view-no-comments" src="https://user-images.githubusercontent.com/20842182/81717435-8c435300-9448-11ea-8ba8-609d10b6e39a.png">

### Todo
- [x] Apply styles to Single Video View pages as per the new designs
- [x] Apply mobile and tablet styles to Single Video View pages as per the new designs
- [x] Add the video to the Single View page
- [x] Add video title, date, views and length to the video as per the design
- [x] Add related video function
- [x] Add comment function
- [x] Remove page banner

### To Fix
- [x] Fix global styling issues
