### ISSUE TITLE
Videos Archive page - Enhancements

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx-videos#8]
### Is your enhancement related to a problem? Please describe.
All video templates are not updated and they all have styling issues and missing information.

### Describe the solution you'd like
There are new designs that offer a solutions to this problems and update all the templates

### Designs
[Video landing page with filters](https://projects.invisionapp.com/d/main?origin=v7#/console/19153622/416948511/preview?scrollOffset=400)
<img width="428" alt="video-landing-page-with-filters" src="https://user-images.githubusercontent.com/20842182/81705119-aa0abb00-943c-11ea-9c59-49b04ea5bc6f.png">

[Video landing page without filters](https://projects.invisionapp.com/d/main?origin=v7#/console/19153622/416951881/preview?scrollOffset=400)
<img width="428" alt="video-landing-page-without-filters" src="https://user-images.githubusercontent.com/20842182/81705182-c149a880-943c-11ea-9657-c7a7a52020b7.png">

### Todo
- [x] Apply styles to Video Landing pages as per the new designs
- [x] Apply mobile and tablet styles to Video Landing pages as per the new designs
- [x] Add "Tags" Facet.
- [x] Add video length meta tag
- [x] Add an option to enable or disable the video modals
- [x] Add video play button on Featured image of each video

### To Fix
- [x] Fix the banner title to show the videos landing page title "All Videos"
- [x] Add the Results counts title
- [x] Fix Grid distribution and spacing
- [x] Fix Video Landing page margin bottom to match the design
