### ISSUE TITLE
Video Single Category Archive page - Enhancements

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx-videos#9]
### Is your enhancement related to a problem? Please describe.
Video Category template is not updated and have styling issues and missing information.

### Describe the solution you'd like
There is a new design for this Archive page that offer a solution to this problem and update the template

### Designs
[Video Single Category](https://projects.invisionapp.com/d/main?origin=v7#/console/19153622/417127787/inspect?scrollOffset=400)
<img width="428" alt="videos-single-category" src="https://user-images.githubusercontent.com/20842182/81710139-86497400-9440-11ea-9c14-e3af2eb56fa6.png">

### Todo
- [x] Apply styles to Video Single Category page as per the new design
- [x] Apply mobile and tablet styles to Video Single Category page as per the new design
- [x] Add video play button on Featured image of each video

### To Fix
- [x] Fix the banner title to show the videos category title
- [x] Remove category filtering from top to adapt page to the new design
- [x] Fix Grid distribution and spacing
- [x] Fix Video Category page margin bottom to match the design
